services:
  ##### NGINX (reverse proxy only) #####
  nginx:
    image: jc21/nginx-proxy-manager:2.13.0
    restart: unless-stopped

    environment:
      TZ: Europe/Ljubljana

    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

    networks:
      - docker-net


  ##### POSTGRES (application DB) #####
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb

    env_file:
      - .env

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - docker-net


  ##### MINIO #####
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - minio_data:/data

    command: server /data --console-address ":9001"

    networks:
      - docker-net


  ##### OPENSEARCH NODE 1 #####
  opensearch-node1:
    image: opensearchproject/opensearch:3.4.0
    restart: unless-stopped

    env_file:
      - .env

    environment:
      cluster.name: opensearch-cluster
      node.name: opensearch-node1
      discovery.seed_hosts: opensearch-node1,opensearch-node2
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    volumes:
      - opensearch-data1:/usr/share/opensearch/data

    networks:
      - docker-net


  ##### OPENSEARCH NODE 2 #####
  opensearch-node2:
    image: opensearchproject/opensearch:3.4.0
    restart: unless-stopped

    env_file:
      - .env

    environment:
      cluster.name: opensearch-cluster
      node.name: opensearch-node2
      discovery.seed_hosts: opensearch-node1,opensearch-node2
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    volumes:
      - opensearch-data2:/usr/share/opensearch/data

    networks:
      - docker-net


  ##### KEYCLOAK DATABASE #####
  keycloak-db:
    image: postgres:18
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_PASSWORD}

    volumes:
      - keycloak_db_data:/var/lib/postgresql

    networks:
      - docker-net


  ##### KEYCLOAK #####
  keycloak:
    image: keycloak/keycloak:26.5
    restart: unless-stopped

    env_file:
      - .env

    command: start

    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_PASSWORD}

    depends_on:
      - keycloak-db

    networks:
      - docker-net


##### VOLUMES #####
volumes:
  nginx_data:
  nginx_letsencrypt:
  db_data:
  minio_data:
  opensearch-data1:
  opensearch-data2:
  keycloak_db_data:


##### NETWORKS #####
networks:
  docker-net: