services:
  ##### NGINX MANAGER #####
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped

    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port

    environment:
      TZ: "Europe/Ljubljana"

    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

##### POSTGRES DATABASE #####
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb  # optional, improves performance for some workloads

    env_file:
      - ./.env

    volumes:
      - db_data:/var/lib/postgresql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
     - docker-net

##### PGADMIN #####
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
     - ./.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
     - docker-net
    depends_on:
     - db

##### MINIO #####
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # API / S3
      - "9001:9001"  # Web console
    env_file:
     - ./.env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - docker-net


##### OPENSEARCH #####
##### node 1
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    env_file:
     - ./.env
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - docker-net # All of the containers will join the same Docker bridge network
##### node 2
  opensearch-node2:
    image: opensearchproject/opensearch:latest # This should be the same image used for opensearch-node1 to avoid issues
    container_name: opensearch-node2
    env_file:
     - ./.env
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - docker-net
##### dashboard
  opensearch-dashboards:
    depends_on:
     - opensearch-node1
     - opensearch-node2
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - docker-net

##### KEYCLOAK #####
  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql
    networks:
      - docker-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    env_file:
     - ./.env
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    restart: always
    networks:
      - docker-net

##### BACKEND #####
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped

    env_file:
      - ./.env

    ports:
      - "3000:3000" # remove later when nginx is wired

    depends_on:
      - db
      - minio
      - keycloak

    networks:
      - docker-net

##### volumes
volumes:
  nginx_data:
  nginx_letsencrypt:
  
  db_data:
  pgadmin_data:
  
  opensearch-data1:
  opensearch-data2:

  minio_data:

  keycloak_db_data:

##### networks
networks:
  docker-net: